# Generated by Django 4.2.27 on 2026-02-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(max_length=200)),
                ('numero_colaboradores', models.IntegerField(default=0)),
                ('horas_semana', models.IntegerField(default=0)),
                ('horas_dia', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'maestro_cargo',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('procesos', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'maestro_concepto',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_horario', models.IntegerField(unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'maestro_horario',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.BigIntegerField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, db_column='cargo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='logistica.cargo', to_field='id_cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'maestro_empleado',
            },
        ),
        migrations.CreateModel(
            name='CargoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='logistica.cargo', to_field='id_cargo')),
                ('horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='logistica.horario', to_field='id_horario')),
            ],
            options={
                'verbose_name': 'Cargo-Horario',
                'verbose_name_plural': 'Cargos-Horarios',
                'db_table': 'maestro_cargo_horario',
                'unique_together': {('cargo', 'horario')},
            },
        ),
    ]
