# Generated by Django 4.2.27 on 2026-02-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_modelos_maestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='excluido',
            field=models.BooleanField(default=False, help_text='Si está activo, este empleado se omite completamente del análisis de huellero.'),
        ),
    ]
