# Generated by Django 4.2.27 on 2026-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_empleado_campo_excluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('marcaciones_am', models.SmallIntegerField(default=0)),
                ('marcaciones_pm', models.SmallIntegerField(default=0)),
                ('hora_ingreso', models.CharField(blank=True, max_length=10)),
                ('hora_salida', models.CharField(blank=True, max_length=10)),
                ('total_horas', models.FloatField(blank=True, null=True)),
                ('limite_horas_dia', models.CharField(blank=True, max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('observaciones_1', models.CharField(blank=True, default='', max_length=500, verbose_name='Observación manual')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'registro_asistencia',
                'ordering': ['codigo', 'fecha', 'hora_ingreso'],
                'unique_together': {('codigo', 'fecha', 'hora_ingreso')},
            },
        ),
    ]
