# Generated by Django 4.2.7 on 2026-01-28 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('logistica', 'Logística'), ('supervision', 'Supervisión'), ('produccion', 'Producción'), ('mantenimiento', 'Mantenimiento'), ('admin', 'Administrador')], default='logistica', max_length=50, verbose_name='Área asignada')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
